## 1. import numpy

In [2]:
import numpy as np

## 2. 查看numpy版本以及配置

In [3]:
print(np.__version__)
#np.show_config()

1.15.1


## 3. 创建长度为10的空向量

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. 查看数组内存

In [5]:
a = np.zeros((10,10))
print("bytes:%d" %(a.size*a.itemsize))
print("itemsize:%d" %a.itemsize)
print("size:%d" %a.size)
print(a)

bytes:800
itemsize:8
size:100
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 5. 得到numpy文档中对add函数的解释

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个除了第五个元素其他元素为空的向量

In [7]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个从49到89的向量

In [8]:
np.arange(49,89)

array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88])

## 8. 翻转一个向量

In [9]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 9. 创建一个值从0到8的3x3的矩阵

In [10]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. 找到数组中非0元素的索引

In [11]:
np.nonzero([0,1,2,0,6])

(array([1, 2, 4]),)

## 11. 创建一个3x3的单位矩阵

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个3x3x3的随机数组

In [13]:
np.random.random((3,3,3))

array([[[0.48155327, 0.65171797, 0.82860222],
        [0.73690949, 0.15256852, 0.73162915],
        [0.08686242, 0.02500459, 0.67728288]],

       [[0.12464313, 0.99527825, 0.04405782],
        [0.5284984 , 0.66302178, 0.50805871],
        [0.10276364, 0.9852179 , 0.74656985]],

       [[0.00585682, 0.10319613, 0.70873003],
        [0.92275647, 0.38649135, 0.46127319],
        [0.7763519 , 0.12624799, 0.37329482]]])

## 13. 创建10x10的随机数数组并且找到最大值与最小值

In [14]:
a = np.random.random((10,10))
a_min, a_max = a.min(),a.max()
print(a_min, a_max)
# print(a)

0.011936016452137599 0.992589180834719


## 14. 创建一个长度为30随机数组并找出他的平均值

In [15]:
a = np.random.random(30)
Mean = a.mean()
print(Mean)

0.47284790567871515


## 15. 创建一个二维数组，其中边界值为1，其余值为0

In [16]:
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. 对于一个存在在数组，添加一个用0填充的边界

In [17]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. 以下表达式运行结果是什么？
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18. 创建一个5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [19]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


> 这里我们来讲一下，np.diag这个函数，这个函数有些许的意思。
> - 当你传入的参数是一个一维数组时，你得到的是一个以该一维数组为对角线的二维数组
> - 当你传入的参数是一个二维数组时，你得到的是一个以对角线的一维数组
> - 参数k，是用来标示对角线的位置，如果是-1，就是对角线下面一阶，如果是1，则是对角线上面一阶，以此类推。

**我们来看一个例子**

In [20]:
# examples
a = np.arange(4).reshape((2,2))
b = np.arange(2)
print(a)
print(np.diag(a))
print(b)
print(np.diag(b))

[[0 1]
 [2 3]]
[0 3]
[0 1]
[[0 0]
 [0 1]]


## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [21]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


> 在这里，我们讲一下python中双冒号的用法。
> - 在最基础的list中，双冒号代表的意思是（从哪里开始：到哪里结束：每几部取一个元素）
> - 在numpy的多维数组中，双冒号的作用是：（第几层::,第几行::，第几列::）
> - 如果是负数的话，则是反向取值，应用的话就是字符串的翻转。

**然后我们看一下例子**

In [22]:
# examples
a = np.arange(24).reshape((3,2,4)) #生成一个3x2x4的多维数组
print(a)
print(a[::,::2,::2]) #遍历每一层，每两行，每两列，取值
print(a[::2,::2,::2]) #每两层，每两行，每两列，取值
print(a[1::2,::2,::2]) #从第一层开始每两层，每两行，每两列，取值
str = "欢迎大家给我点star，嘻嘻嘻"
print(str[::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2]]

 [[ 8 10]]

 [[16 18]]]
[[[ 0  2]]

 [[16 18]]]
[[[ 8 10]]]
嘻嘻嘻，rats点我给家大迎欢


## 20. 考虑一个 (6,7,8) 形状的数组，求其第100个元素的索引(x,y,z)

In [23]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

> 这里我们讲一下unravel_index这个函数：
> - 这个函数是用来求取数组中某个元素的位置
> - indices:要求取索引的数据，如果是一个数字，则返回一个元组代表了他的索引，如果是一个数组，则返回一个多维数组，每个小数组都代表了每一维的索引。
> - dims:表示要求取的索引对应数组的维度

**我们来看个例子**

In [24]:
np.unravel_index(indices=[99,100,101], dims=(6, 7, 8))

(array([1, 1, 1]), array([5, 5, 5]), array([3, 4, 5]))

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [25]:
np.tile(np.array([[0, 1],[1, 0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

> （没错，又是我，小声bb）这次我们来讲一下np.tile
> - 首先，这个函数是用来按某种方式重复某个矩阵从而实现矩阵的扩展
> - 第一个参数是：要扩展的矩阵
> - 第二个参数是：如何扩建，如果传入的是元组（1,2），那么就是行重复一次，列重复2次。如果传入的是一个数，那么就是列扩展。

**我们来看个小例子**

In [26]:
print(np.tile(np.array([[0,1]]), (1,2))) #行1，列2
print(np.tile(np.array([[0,1]]), (2,1))) #行2，列1
print(np.tile(np.array([[0,1]]), 2)) #列2

[[0 1 0 1]]
[[0 1]
 [0 1]]
[[0 1 0 1]]


## 22. 对一个5x5的随机矩阵做归一化

In [27]:
a = np.random.random((5, 5))
a_max, a_min = a.max(), a.min()
a = (a - a_min)/(a_max - a_min)
print(a)

[[0.81164515 0.5539399  0.45904706 0.51668545 0.04324913]
 [0.04304045 0.26775554 0.49335313 0.77580874 0.31502485]
 [0.89776818 0.7698457  0.01757578 0.69585548 1.        ]
 [0.46207914 0.45849154 0.9343307  0.16686542 0.02330326]
 [0.76498712 0.82052924 0.34450334 0.96479073 0.        ]]


## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [28]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


> 我们讲一下 np.dtype
> - 这个函数是用来自定义我们的数据类型的

## 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么

In [29]:
np.dot(np.ones((5,3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [30]:
np.ones((5,3))@np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## 25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [31]:
a = np.arange(11)
a = a[8:2:-1]
print(a)

[8 7 6 5 4 3]


## 26. 下面脚本运行后的结果是什么
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [32]:
print(sum(range(5), -1))

9


In [33]:
from numpy import *
print(sum(range(5), -1))

10


> 解释：
> 为什么是这样呢？
> - 首先，我们先了解一下python标准库的sum函数，sum函数的第二个参数表示，求和以后再加一个数
> - 但是，显然NumPy对sum函数有不同的实现，他的第二个参数是axis也就是求和的行或列。

**让我们看个小例子**

In [34]:
a = np.arange(12).reshape((3, 4))
print(a)
print(sum(a, axis=-1))
print(sum(a, axis=1))
print(sum(a, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[ 6 22 38]
[12 15 18 21]


## 27. 考虑一个整数向量Z,下列表达合法的是哪个
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [35]:
z = np.arange(5)
print(z**z)

[  1   1   4  27 256]


In [36]:
print(2<<z>>2) #bit shift

[0 1 2 4 8]


In [37]:
print(z<-z)

[False False False False False]


In [38]:
print(1j*z) #复数

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [39]:
print(z/1/1)

[0. 1. 2. 3. 4.]


In [40]:
# print(z<z>z) wrong

> 我们解释一下位运算这里的东西：
> - 左移运算就是乘2的位数
> - 右移运算就是除以2的位数
---
> 还有numpy中的j表示的是复数

## 28. 下列表达式的结果分别是什么?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) / np.array(0)

In [41]:
np.array(0) // np.array(0)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [42]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

> **Nan：Not a number** 
**Inf：Infinity(无穷大）** 
当然容易搞混的还有None，None是python中用于标识空缺数据，Nan是nunpy和pandas中用于标识空缺数据，None是一个python特殊的数据类型， **但是NaN却是用一个特殊的float**

## 29. 如何从零位对浮点数组做舍入

In [43]:
a = np.random.uniform(-10, +10, 10)
print(a)
print (np.copysign(np.ceil(np.abs(a)), a))

[ 5.81355585  4.84324912  0.85135556  9.95197876 -2.20742748  8.87985479
  9.73768559  2.70001196 -8.84696019 -8.6432732 ]
[ 6.  5.  1. 10. -3.  9. 10.  3. -9. -9.]


> 讲解：
> - 首先,np.ceil是向上取整
> - 然后，copysign(a, b)是将b的符号赋值给a的元素
> 为什么要这么做呢？
> 我们可以想一下：
> 如果a是个负数，我们不取绝对值，直接取整，那么会将位数舍去，但是如果a是个正数，他又会向上取整。


## 30. 如何找到两个数组中的共同元素?

In [46]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)
print(np.intersect1d(a, b))

[6 4 0 7 3 7 4 2 4 6]
[4 1 4 7 4 6 9 2 3 1]
[2 3 4 6 7]


> np.intersect1d是用来求取交集的函数

## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)

In [47]:
defaults = np.seterr(all="ignore")
np.zeros(1)/0

array([nan])