## 1. import numpy

In [1]:
import numpy as np

## 2. 查看numpy版本以及配置

In [2]:
print(np.__version__)
#np.show_config()

1.15.1


## 3. 创建长度为10的空向量

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. 查看数组内存

In [4]:
a = np.zeros((10,10))
print("bytes:%d" %(a.size*a.itemsize))
print("itemsize:%d" %a.itemsize)
print("size:%d" %a.size)
print(a)

bytes:800
itemsize:8
size:100
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 5. 得到numpy文档中对add函数的解释

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个除了第五个元素其他元素为空的向量

In [6]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个从49到89的向量

In [7]:
np.arange(49,89)

array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88])

## 8. 翻转一个向量

In [8]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 9. 创建一个值从0到8的3x3的矩阵

In [9]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. 找到数组中非0元素的索引

In [10]:
np.nonzero([0,1,2,0,6])

(array([1, 2, 4]),)

## 11. 创建一个3x3的单位矩阵

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个3x3x3的随机数组

In [12]:
np.random.random((3,3,3))

array([[[0.89992376, 0.37997805, 0.0230684 ],
        [0.65057075, 0.71558852, 0.41638061],
        [0.28274655, 0.73107634, 0.32849742]],

       [[0.18615076, 0.35049821, 0.58891342],
        [0.56775621, 0.67701176, 0.32177441],
        [0.19489924, 0.02764411, 0.68089986]],

       [[0.58158062, 0.70827401, 0.40164885],
        [0.98678198, 0.93278335, 0.09035683],
        [0.48468222, 0.41780076, 0.78031366]]])

## 13. 创建10x10的随机数数组并且找到最大值与最小值

In [13]:
a = np.random.random((10,10))
a_min, a_max = a.min(),a.max()
print(a_min, a_max)
# print(a)

0.006291477373849053 0.989993206855313


## 14. 创建一个长度为30随机数组并找出他的平均值

In [14]:
a = np.random.random(30)
Mean = a.mean()
print(Mean)

0.5362556116717234


## 15. 创建一个二维数组，其中边界值为1，其余值为0

In [15]:
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. 对于一个存在在数组，添加一个用0填充的边界

In [16]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. 以下表达式运行结果是什么？
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18. 创建一个5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [18]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


> 这里我们来讲一下，np.diag这个函数，这个函数有些许的意思。
> - 当你传入的参数是一个一维数组时，你得到的是一个以该一维数组为对角线的二维数组
> - 当你传入的参数是一个二维数组时，你得到的是一个以对角线的一维数组
> - 参数k，是用来标示对角线的位置，如果是-1，就是对角线下面一阶，如果是1，则是对角线上面一阶，以此类推。

**我们来看一个例子**

In [19]:
# examples
a = np.arange(4).reshape((2,2))
b = np.arange(2)
print(a)
print(np.diag(a))
print(b)
print(np.diag(b))

[[0 1]
 [2 3]]
[0 3]
[0 1]
[[0 0]
 [0 1]]


## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [20]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


> 在这里，我们讲一下python中双冒号的用法。
> - 在最基础的list中，双冒号代表的意思是（从哪里开始：到哪里结束：每几部取一个元素）
> - 在numpy的多维数组中，双冒号的作用是：（第几层::,第几行::，第几列::）
> - 如果是负数的话，则是反向取值，应用的话就是字符串的翻转。

**然后我们看一下例子**

In [21]:
# examples
a = np.arange(24).reshape((3,2,4)) #生成一个3x2x4的多维数组
print(a)
print(a[::,::2,::2]) #遍历每一层，每两行，每两列，取值
print(a[::2,::2,::2]) #每两层，每两行，每两列，取值
print(a[1::2,::2,::2]) #从第一层开始每两层，每两行，每两列，取值
str = "欢迎大家给我点star，嘻嘻嘻"
print(str[::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2]]

 [[ 8 10]]

 [[16 18]]]
[[[ 0  2]]

 [[16 18]]]
[[[ 8 10]]]
嘻嘻嘻，rats点我给家大迎欢


## 20. 考虑一个 (6,7,8) 形状的数组，求其第100个元素的索引(x,y,z)

In [22]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

> 这里我们讲一下unravel_index这个函数：
> - 这个函数是用来求取数组中某个元素的位置
> - indices:要求取索引的数据，如果是一个数字，则返回一个元组代表了他的索引，如果是一个数组，则返回一个多维数组，每个小数组都代表了每一维的索引。
> - dims:表示要求取的索引对应数组的维度

**我们来看个例子**

In [23]:
np.unravel_index(indices=[99,100,101], dims=(6, 7, 8))

(array([1, 1, 1]), array([5, 5, 5]), array([3, 4, 5]))

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [24]:
np.tile(np.array([[0, 1],[1, 0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

> （没错，又是我，小声bb）这次我们来讲一下np.tile
> - 首先，这个函数是用来按某种方式重复某个矩阵从而实现矩阵的扩展
> - 第一个参数是：要扩展的矩阵
> - 第二个参数是：如何扩建，如果传入的是元组（1,2），那么就是行重复一次，列重复2次。如果传入的是一个数，那么就是列扩展。

**我们来看个小例子**

In [25]:
print(np.tile(np.array([[0,1]]), (1,2))) #行1，列2
print(np.tile(np.array([[0,1]]), (2,1))) #行2，列1
print(np.tile(np.array([[0,1]]), 2)) #列2

[[0 1 0 1]]
[[0 1]
 [0 1]]
[[0 1 0 1]]


## 22. 对一个5x5的随机矩阵做归一化

In [26]:
a = np.random.random((5, 5))
a_max, a_min = a.max(), a.min()
a = (a - a_min)/(a_max - a_min)
print(a)

[[0.31050148 0.         0.3542466  1.         0.87335508]
 [0.58811378 0.38024073 0.47825648 0.51090794 0.38810391]
 [0.03188368 0.57819473 0.00935861 0.4315329  0.86883833]
 [0.82391544 0.79130716 0.32995146 0.45866851 0.711522  ]
 [0.51218292 0.61812194 0.56448913 0.67780123 0.1102782 ]]


## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [27]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


> 我们讲一下 np.dtype
> - 这个函数是用来自定义我们的数据类型的

## 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么

In [28]:
np.dot(np.ones((5,3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [29]:
np.ones((5,3))@np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## 25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [30]:
a = np.arange(11)
a = a[8:2:-1]
print(a)

[8 7 6 5 4 3]


## 26. 下面脚本运行后的结果是什么
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5), -1))

9


In [32]:
from numpy import *
print(sum(range(5), -1))

10


> 解释：
> 为什么是这样呢？
> - 首先，我们先了解一下python标准库的sum函数，sum函数的第二个参数表示，求和以后再加一个数
> - 但是，显然NumPy对sum函数有不同的实现，他的第二个参数是axis也就是求和的行或列。

**让我们看个小例子**

In [33]:
a = np.arange(12).reshape((3, 4))
print(a)
print(sum(a, axis=-1))
print(sum(a, axis=1))
print(sum(a, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[ 6 22 38]
[12 15 18 21]


## 27. 考虑一个整数向量Z,下列表达合法的是哪个
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
z = np.arange(5)
print(z**z)

[  1   1   4  27 256]


In [35]:
print(2<<z>>2) #bit shift

[0 1 2 4 8]


In [36]:
print(z<-z)

[False False False False False]


In [37]:
print(1j*z) #复数

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [38]:
print(z/1/1)

[0. 1. 2. 3. 4.]


In [39]:
# print(z<z>z) wrong

> 我们解释一下位运算这里的东西：
> - 左移运算就是乘2的位数
> - 右移运算就是除以2的位数
---
> 还有numpy中的j表示的是复数

## 28. 下列表达式的结果分别是什么?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) / np.array(0)

In [40]:
np.array(0) // np.array(0)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [41]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

> **Nan：Not a number** 
**Inf：Infinity(无穷大）** 
当然容易搞混的还有None，None是python中用于标识空缺数据，Nan是nunpy和pandas中用于标识空缺数据，None是一个python特殊的数据类型， **但是NaN却是用一个特殊的float**

## 29. 如何从零位对浮点数组做舍入

In [42]:
a = np.random.uniform(-10, +10, 10)
print(a)
print (np.copysign(np.ceil(np.abs(a)), a))

[-9.2195802   7.74434787 -8.21217022  7.42616471 -5.62751054  8.25881339
  5.64084902  0.58462815 -0.84283827 -2.19910293]
[-10.   8.  -9.   8.  -6.   9.   6.   1.  -1.  -3.]


> 讲解：
> - 首先,np.ceil是向上取整
> - 然后，copysign(a, b)是将b的符号赋值给a的元素
> 为什么要这么做呢？
> 我们可以想一下：
> 如果a是个负数，我们不取绝对值，直接取整，那么会将位数舍去，但是如果a是个正数，他又会向上取整。


## 30. 如何找到两个数组中的共同元素?

In [43]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)
print(np.intersect1d(a, b))

[0 9 3 0 5 7 2 8 6 5]
[6 9 0 7 9 4 4 1 9 5]
[0 5 6 7 9]


> np.intersect1d是用来求取交集的函数

## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)

In [44]:
defaults = np.seterr(all="ignore")
np.zeros(1)/0

array([nan])

## 32. 下面的表达式是正确的吗?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [46]:
print(np.sqrt(-1))

nan


In [47]:
print(np.emath.sqrt(-1))

1j


> 讲解一下：emath是什么？
> - NumPy中的自动域函数
> - 可以更友好地使用数学函数，而不去考虑他的定义域
> - 比如说：当我们对-1使用最初时的sqrt函数，会得到返回值nan，但是如果使用emath中的函数，他会为我们返回一个复数。相同的比如说对数函数。

## 33. 如何得到昨天，今天，明天的日期?

In [48]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

2019-04-10


In [49]:
today = np.datetime64('today', 'D')
print(today)

2019-04-11


In [50]:
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2019-04-12


> 日期时间与时间增量
> - numpy从1.7开始，将时间变量加入到核心数据组中，但是由于python标准时间库中已经将datetime包含了进去，所以他叫做datetime64
> - datetime的第二个参数指定了datetime的单位。日期单位是年（'Y'），月（'M'），周（'W'）和天（'D'），而时间单位是小时（'h'），分钟（'m'） ），秒（'s'），毫秒（'ms'）和一些额外的SI前缀基于秒的单位。
> - NumPy允许减去两个Datetime值，这个操作产生一个带有时间单位的数字。 由于NumPy的核心没有物理量系统，因此创建了timedelta64数据类型以补充datetime64。

**下面看个小例子**

In [51]:
np.datetime64('1999-10-03', 'M')

numpy.datetime64('1999-10')

In [52]:
np.datetime64('1999-10', 'D')

numpy.datetime64('1999-10-01')

In [53]:
my_birthday = np.datetime64("1999-10-03", "D")
your_birthday = np.datetime64("1998-08-24", "D")
my_birthday - your_birthday

numpy.timedelta64(405,'D')

## 34. 如何得到所有与2016年7月对应的日期

In [54]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [55]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(B)
np.add(A,B,out=B)
print(B)

[2. 2. 2.]
[3. 3. 3.]


In [56]:
print(A)
np.divide(A,2,out=A)
print(A)

[1. 1. 1.]
[0.5 0.5 0.5]


In [57]:
print(A)
np.negative(A,out=A)
print(A)

[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]


In [58]:
print(A)
np.multiply(A,B,out=A)
print(A)

[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


## 36. 用五种不同的方法去提取一个随机数组的整数部分

In [59]:
a = np.random.uniform(-10, 10, 10)
print(a)

[-3.37597519 -9.20412039 -7.39652038  5.3149112  -0.94684315 -4.35904728
 -8.44978401 -5.22374173 -8.03957875 -3.01474002]


In [60]:
print(a - a%1)

[ -4. -10.  -8.   5.  -1.  -5.  -9.  -6.  -9.  -4.]


In [61]:
np.floor(a)

array([ -4., -10.,  -8.,   5.,  -1.,  -5.,  -9.,  -6.,  -9.,  -4.])

In [62]:
np.ceil(a) - 1

array([ -4., -10.,  -8.,   5.,  -1.,  -5.,  -9.,  -6.,  -9.,  -4.])

In [63]:
a.astype(int)

array([-3, -9, -7,  5,  0, -4, -8, -5, -8, -3])

In [64]:
np.trunc(a)

array([-3., -9., -7.,  5., -0., -4., -8., -5., -8., -3.])

> 讲解一下：
> - np.floor 向下取整
> - np.trunc 截取元素，也就是取最接近的整数。参数为array like的元素

## 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [65]:
a = np.arange(5).astype(float64)
a = np.tile(a, (4,1))
print(a)
print(type(a))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
<class 'numpy.ndarray'>


In [66]:
b = np.zeros((5,5))
b += np.arange(5)
print(b)
print(type(b))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
<class 'numpy.ndarray'>


## 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [67]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [68]:
np.random.uniform(0,1, 10)

array([0.58122768, 0.13288027, 0.50110287, 0.00524711, 0.28704599,
       0.61044677, 0.2941267 , 0.00950536, 0.20469508, 0.51079987])

In [69]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
# 这是当时我看的那个人写的答案，但是在我查了np.linspace的用法以后，我认为他的答案是错的，他不满足随机

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


> 讲解一下：
> - np.linspace()是用来产生一个向量。
> - 参数：start：起始值；end：最大值；endpoint：是否包含最大值，也就是end；retstep：步长
> - 也正是因为这个步长，所以我说他的方法是错误的。

## 40. 创建一个长度为10的随机向量，并将其排序

In [70]:
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.28220182 0.56398255 0.35518135 0.25051765 0.36151273 0.09864115
 0.94357957 0.15593073 0.36680686 0.99986116]
[0.09864115 0.15593073 0.25051765 0.28220182 0.35518135 0.36151273
 0.36680686 0.56398255 0.94357957 0.99986116]


## 41.对于一个小数组，如何用比 np.sum更快的方式对其求和

In [71]:
a = np.arange(10)
import time
begin = time.time()
np.add.reduce(a)
end = time.time()
print(end - begin)

6.175041198730469e-05


In [72]:
begin = time.time()
np.sum(a)
end = time.time()
print(end - begin)

0.0001163482666015625


> 讲解一下：
> - 在小阵列的数据上，np.add.reduce是要比np.sum快的，但是，当数据规模一上升，差异就消失了。
> - 为什么呢？简单的说就是因为np.sum实际上调用的就是reduce，所差的时间也在参数处理和函数调用上。

## 42. 对于两个随机数组A和B，检查它们是否相等

In [73]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


> 讲解一下：
> - numpy的allclose方法，比较两个array是不是每一元素都相等，默认在1e-05的误差范围内

np.array_equal(A, B)

## 43. 创建一个只读数组(read-only)

In [74]:
a = np.arange(5)
print(a)
a.flags.writeable = False
a[0] = 1

[0 1 2 3 4]


ValueError: assignment destination is read-only

## 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

## 45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [ ]:
a = np.random.randint(0, 5, 10)
print(a)
a[a.argmax()] = 1
print(a)

## 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

> 讲解一下：
> - np.meshgrid()其实就是在高维空间画网格用的函数
> - 好多文章都说画网格，其实刚开始我是没有理解的，不过没有关系，我们来看个小栗子就好了

In [ ]:
a = np.random.randint(0, 5, 4)
b = np.random.randint(0, 8, 4)
print(a)
print(b)
[x, y] = np.meshgrid(a, b) # x是横向的线， y是纵向的线
print(x)
print(y)

# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

> - substract,multiply等函数叫做ufunc，也就是通用函数
> - ufunc.outer是Apply the ufunc op to all pairs (a, b) with a in A and b in B.简单的说就是应用ufunc到每一对数据上
> - np.linalg.det是用来求行列式的，但是后两个维度必须是方阵

**看个例子**

In [ ]:
a = np.arange(5)
b = a + 1
print(a)
print(b)
np.subtract.outer(a, b)

## 48. 打印每个numpy标量类型的最小值和最大值

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

> - np.iinfo() Machine limits for integer types.
> - np.finfo() Machine limits for floating point types.
> - np.finfo().eps 所能表示的最小正数

## 49. 如何打印一个数组中的所有数值

In [76]:
# np.set_printoptions(threshold=np.nan)
Z = np.zeros((50,50))
print (Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [77]:
np.set_printoptions(threshold=np.nan)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

> - 我们会发现，如果我们ndarray的数据一旦比较多的时候，我们在print的时候就会被折叠
> - 这时候，我们就要使用np.setprintoptions()了
> - - precision:输出结果保留精度的位数
- - threshold:array数量的个数在小于threshold的时候不会被折叠
- - edgeitems:在array已经被折叠后，开头和结尾都会显示edgeitems个数
- - formatter:这个很有意思，像python3里面str.format(),就是可以对你的输出进行自定义的格式化

**如果不明白，可以看一下上面的例子**

## 50. 给定标量时，如何找到数组中最接近标量的值

In [80]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

70


## 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [81]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


## 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [86]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.13430989 0.01417921 0.9577445  0.04334651 0.43132368 0.93087448
  0.49127828 0.76054638 0.66448973 0.37966756]]
[[0.84171985 0.02230866 0.13042557 0.58681136 0.77857736 0.448066
  0.29941031 0.61532274 0.07976058 0.77077684]]


> np.atleast_2d()是用来改变维度的，就是直接将其视为某个维度

**比如说：**

In [87]:
np.atleast_2d([1])

array([[1]])

In [88]:
np.atleast_3d([1])

array([[[1]]])

## 53. 如何将32位的浮点数(float)转换为对应的整数(integer)

In [95]:
a = np.arange(5, dtype=int32)
print(a)
a = a.astype(np.float32, copy=False)
print(a)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


## 54. 如何读取以下文件
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [97]:
np.genfromtxt(fname="./data.txt", dtype=np.int32, delimiter=',')

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int32)

> np.genfromtxt()函数：
> - 用来将文件转换为表格
> - 参数解析：
>  - autostrip:是否自动去除空格
>  - delimiter:分割符
>  - fname:文件路径只有这个是必选的
>  - miss:缺失值
>  - missvalues:缺失值替换为什么
>  - dtype:数据类型

这里只列出常用的参数，如果大家还想深入了解，那么请大家看[这里](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html)

## 55. 对于numpy数组，enumerate的等价操作是什么

In [101]:
Z = np.arange(9).reshape(3,3)
print(Z)
print("----------")
for index, value in np.ndenumerate(Z):
    print (index, value)
print("----------")
for index in np.ndindex(Z.shape):
    print (index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
----------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**是什么呢？显然就是索引和值，不过多维数组的索引是一个tuple**

## 56. 生成一个通用的二维Gaussian-like数组

In [102]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 57. 对一个二维数组，如何在其内部随机放置p个元素?

In [106]:
a = np.zeros((10, 10))
print(a)
np.put(a, np.random.choice(range(10*10), 8, replace=False), 1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


> np.random.choice() 可以从一个int数字或1维array里随机选取内容，并将选取结果放入n维array中返回。
> - 参数：
>  - a : 如果是一维数组，就表示从这个一维数组中随机采样；如果是int型，就表示从0到a-1这个序列中随机采样。 
>  - size : 采样结果的数量，默认为1.可以是整数，表示要采样的数量；也可以为tuple，如(m, n, k)，则要采样的数量为m * n * k，size为(m, n, k)。 
>  - replace : boolean型，采样的样本是否要更换？这个地方我不太理解，测了一下发现replace指定为True时，采样的元素会有重复；当replace指定为False时，采样不会重复。 
>  - p : 一个一维数组，制定了a中每个元素采样的概率，若为默认的None，则a中每个元素被采样的概率相同。

## 58. 减去一个矩阵中的每一行的平均值

In [107]:
X = np.random.rand(5, 10)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.14510781 0.75281345 0.85436249 0.32663009 0.40053696 0.65682376
  0.62395091 0.99332502 0.02582292 0.69786946]
 [0.82748041 0.14938315 0.7738583  0.98442218 0.53311065 0.09129824
  0.42021244 0.10593085 0.43197972 0.56980786]
 [0.20057738 0.27847691 0.27544321 0.02964705 0.07270658 0.05039734
  0.16783396 0.89198137 0.49054742 0.54080551]
 [0.05807512 0.62949833 0.55184512 0.1323936  0.44865394 0.27907512
  0.70984069 0.11103712 0.57294401 0.91250791]
 [0.96588002 0.73807918 0.79376696 0.54947611 0.39775283 0.75979058
  0.1011506  0.74314971 0.46435083 0.8287042 ]]
[[-0.40261647  0.20508916  0.30663821 -0.2210942  -0.14718733  0.10909947
   0.07622662  0.44560073 -0.52190137  0.15014518]
 [ 0.33873203 -0.33936523  0.28510992  0.4956738   0.04436227 -0.39745014
  -0.06853594 -0.38281753 -0.05676866  0.08105948]
 [-0.09926429 -0.02136476 -0.02439846 -0.27019463 -0.2271351  -0.24944433
  -0.13200772  0.59213969  0.19070574  0.24096384]
 [-0.38251198  0.18891123  0.11125803 -0.3081935 

## 59. 如何通过第n列对一个数组进行排序?

In [110]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[7 1 1]
 [6 5 2]
 [0 7 0]]
[[1 1 7]
 [2 5 6]
 [0 0 7]]


**从中可以看出argsort函数返回的是数组值从小到大的索引值**  

**举个例子**

In [115]:
#examples
n = np.random.randint(0,8,5) #1d
print(n)
print(n.argsort())

[7 1 7 6 7]
[1 3 0 2 4]


In [116]:
a = np.random.randint(0, 8, (3,3)) #2d
print(a)
print(a.argsort())

[[1 0 5]
 [7 5 3]
 [7 2 1]]
[[1 0 2]
 [2 1 0]
 [2 1 0]]


## 60. 如何检查一个二维数组是否有空列

In [121]:
Z = np.random.randint(0,3,(3,10))
# print ((~Z.any(axis=0)).any())
print(~Z.any(axis=0).any())

False


> 知识补充：
> - 在NumPy中，～表示对条件判断式的否定
> - any()函数其实是一个OR的过程，就是说A1 OR A2 OR A3 ...
> - all()就是and了

**看不懂？没关系，我们来看个小例子。**

In [123]:
a = np.random.randint(0, 8, (3, 3))
print(a.any(axis=0))
print(~a.any(axis=0))
print(~a.any(axis=0).any())

[ True  True  True]
[False False False]
False
