## 1. import numpy

In [3]:
import numpy as np

## 2. 查看numpy版本以及配置

In [4]:
print(np.__version__)
#np.show_config()

1.15.1


## 3. 创建长度为10的空向量

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. 查看数组内存

In [6]:
a = np.zeros((10,10))
print("bytes:%d" %(a.size*a.itemsize))
print("itemsize:%d" %a.itemsize)
print("size:%d" %a.size)
print(a)

bytes:800
itemsize:8
size:100
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 5. 得到numpy文档中对add函数的解释

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个除了第五个元素其他元素为空的向量

In [8]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个从49到89的向量

In [9]:
np.arange(49,89)

array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88])

## 8. 翻转一个向量

In [10]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 9. 创建一个值从0到8的3x3的矩阵

In [11]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. 找到数组中非0元素的索引

In [12]:
np.nonzero([0,1,2,0,6])

(array([1, 2, 4]),)

## 11. 创建一个3x3的单位矩阵

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个3x3x3的随机数组

In [14]:
np.random.random((3,3,3))

array([[[0.0050927 , 0.67661943, 0.22092062],
        [0.86404563, 0.92950259, 0.49771817],
        [0.50801977, 0.36514152, 0.13409319]],

       [[0.31300884, 0.28410606, 0.25356097],
        [0.19028253, 0.77382199, 0.09791475],
        [0.32235957, 0.27937713, 0.69875678]],

       [[0.84064133, 0.11459145, 0.19865427],
        [0.32694311, 0.71168535, 0.00186135],
        [0.42938914, 0.58301538, 0.28689417]]])

## 13. 创建10x10的随机数数组并且找到最大值与最小值

In [15]:
a = np.random.random((10,10))
a_min, a_max = a.min(),a.max()
print(a_min, a_max)
# print(a)

0.00229609069408121 0.9924644345544039


## 14. 创建一个长度为30随机数组并找出他的平均值

In [16]:
a = np.random.random(30)
Mean = a.mean()
print(Mean)

0.5420331081124832


## 15. 创建一个二维数组，其中边界值为1，其余值为0

In [17]:
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. 对于一个存在在数组，添加一个用0填充的边界

In [18]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. 以下表达式运行结果是什么？
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18. 创建一个5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [20]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


> 这里我们来讲一下，np.diag这个函数，这个函数有些许的意思。
> - 当你传入的参数是一个一维数组时，你得到的是一个以该一维数组为对角线的二维数组
> - 当你传入的参数是一个二维数组时，你得到的是一个以对角线的一维数组
> - 参数k，是用来标示对角线的位置，如果是-1，就是对角线下面一阶，如果是1，则是对角线上面一阶，以此类推。

**我们来看一个例子**

In [21]:
# examples
a = np.arange(4).reshape((2,2))
b = np.arange(2)
print(a)
print(np.diag(a))
print(b)
print(np.diag(b))

[[0 1]
 [2 3]]
[0 3]
[0 1]
[[0 0]
 [0 1]]


## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [22]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


> 在这里，我们讲一下python中双冒号的用法。
> - 在最基础的list中，双冒号代表的意思是（从哪里开始：到哪里结束：每几部取一个元素）
> - 在numpy的多维数组中，双冒号的作用是：（第几层::,第几行::，第几列::）
> - 如果是负数的话，则是反向取值，应用的话就是字符串的翻转。

**然后我们看一下例子**

In [23]:
# examples
a = np.arange(24).reshape((3,2,4)) #生成一个3x2x4的多维数组
print(a)
print(a[::,::2,::2]) #遍历每一层，每两行，每两列，取值
print(a[::2,::2,::2]) #每两层，每两行，每两列，取值
print(a[1::2,::2,::2]) #从第一层开始每两层，每两行，每两列，取值
str = "欢迎大家给我点star，嘻嘻嘻"
print(str[::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2]]

 [[ 8 10]]

 [[16 18]]]
[[[ 0  2]]

 [[16 18]]]
[[[ 8 10]]]
嘻嘻嘻，rats点我给家大迎欢


## 20. 考虑一个 (6,7,8) 形状的数组，求其第100个元素的索引(x,y,z)

In [24]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

> 这里我们讲一下unravel_index这个函数：
> - 这个函数是用来求取数组中某个元素的位置
> - indices:要求取索引的数据，如果是一个数字，则返回一个元组代表了他的索引，如果是一个数组，则返回一个多维数组，每个小数组都代表了每一维的索引。
> - dims:表示要求取的索引对应数组的维度

**我们来看个例子**

In [25]:
np.unravel_index(indices=[99,100,101], dims=(6, 7, 8))

(array([1, 1, 1]), array([5, 5, 5]), array([3, 4, 5]))

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [26]:
np.tile(np.array([[0, 1],[1, 0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

> （没错，又是我，小声bb）这次我们来讲一下np.tile
> - 首先，这个函数是用来按某种方式重复某个矩阵从而实现矩阵的扩展
> - 第一个参数是：要扩展的矩阵
> - 第二个参数是：如何扩建，如果传入的是元组（1,2），那么就是行重复一次，列重复2次。如果传入的是一个数，那么就是列扩展。

**我们来看个小例子**

In [27]:
print(np.tile(np.array([[0,1]]), (1,2))) #行1，列2
print(np.tile(np.array([[0,1]]), (2,1))) #行2，列1
print(np.tile(np.array([[0,1]]), 2)) #列2

[[0 1 0 1]]
[[0 1]
 [0 1]]
[[0 1 0 1]]


## 22. 对一个5x5的随机矩阵做归一化

In [29]:
a = np.random.random((5, 5))
a_max, a_min = a.max(), a.min()
a = (a - a_min)/(a_max - a_min)
print(a)

[[0.49861658 0.24814469 0.07422045 0.67071486 0.37712624]
 [0.48668882 0.91675818 0.09424919 0.48179454 0.59561029]
 [0.17667157 0.06141074 0.778984   0.06688423 0.72796368]
 [0.81015102 1.         0.88143988 0.52912916 0.59502605]
 [0.63053155 0.         0.01760132 0.35330723 0.13910658]]


## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [30]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
